#File tasks/redhat.yml
---
- name: Purge System Ruby (RHEL)
  yum: name=ruby state=absent

- name: Install Ruby Dependencies Packages (RHEL)
  yum: name={{ item }} state=present
  with_items: ruby_builder_rhel_ruby_dependencies
